version: '3.8'

services:
  # Сервис локального Bot API
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      # Обязательно замени на свои данные с my.telegram.org
      TELEGRAM_API_ID: "39723229"
      TELEGRAM_API_HASH: "3e2b8ae519ce46f1e13f286050a56bca"
    command: >
      --local 
      --api-id=$${TELEGRAM_API_ID} 
      --api-hash=$${TELEGRAM_API_HASH} 
      --dir=/data
    volumes:
      - shared_data:/data
    restart: always

  # Твой бот
  bot:
    build: .
    depends_on:
      - telegram-bot-api
    environment:
      BOT_TOKEN: "ТВОЙ_ТОКЕН_БОТА"
      # Бот будет обращаться к API по имени сервиса в сети Docker
      LOCAL_API_URL: "http://telegram-bot-api:8081"
    volumes:
      - shared_data:/data
    restart: always

volumes:
  shared_data:
